import { CheckCircle2, Lightbulb } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StudentQuestionForm } from "@/components/question-forms";
import { Badge } from "@/components/ui/badge";
import { getStudentData } from "@/lib/data";
import { requireSession } from "@/lib/dal";
import { formatChineseDate } from "@/lib/utils";

export default async function QuestionsPage() { const session = await requireSession("student"); const data = await getStudentData(session.user.id); if (!data) return null; return <main className="page-wrap"><PageHeader title="提问答疑" description="说清楚卡住的那一步，AI 先给提示，老师会看到完整问题" /><div className="content-grid two"><section className="panel"><div className="panel-header"><h2>提交新问题</h2></div><div className="panel-body"><StudentQuestionForm /></div></section><aside className="panel"><div className="panel-header"><h2>提问小方法</h2></div><div className="panel-body grid gap-3 text-sm leading-7 text-zinc-600"><p>1. 写出题目让你做什么。</p><p>2. 写出你已经会的部分。</p><p>3. 指出最不明白的那一步。</p><div className="callout">“我需要帮助”会向老师发送额外关注信号，但系统不会做心理诊断。</div></div></aside></div><section className="panel mt-5"><div className="panel-header"><h2>我的问题</h2></div>{data.questions.map((q) => <article className="question-card" key={q.id}><div className="flex flex-wrap gap-2"><Badge tone="blue">{q.subject}</Badge><Badge tone={q.answer ? "green" : "amber"}>{q.answer ? "老师已回复" : "等待老师"}</Badge><Badge>{q.knowledgePoint}</Badge></div><p className="question-text">{q.content}</p><div className="question-ai flex gap-2"><Lightbulb className="mt-1 shrink-0 text-amber-600" size={17} /><span><strong>先试试：</strong>{q.aiHint}</span></div>{q.answer && <div className="mt-3 rounded-md border border-emerald-200 bg-emerald-50 p-4 text-sm leading-7 text-emerald-950"><strong className="flex items-center gap-2"><CheckCircle2 size={17} />李老师回复</strong><p className="mt-2">{q.answer.content}</p></div>}<p className="row-meta mt-3">提交于 {formatChineseDate(q.createdAt, true)}</p></article>)}</section></main>; }
