import { Brain, CircleHelp } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { TeacherQuestionReply } from "@/components/question-forms";
import { Badge } from "@/components/ui/badge";
import { getTeacherData } from "@/lib/data";
import { requireSession } from "@/lib/dal";
import { formatChineseDate } from "@/lib/utils";

export default async function QuestionsPage() { const session = await requireSession("teacher"); const data = await getTeacherData(session.user.id); if (!data) return null; const pending = data.questions.filter((q) => q.status === "pending"); const handled = data.questions.filter((q) => q.status !== "pending"); return <main className="page-wrap"><PageHeader title="学生问题" description="AI 已按学科、知识点与紧急程度整理；教师确认后才会发布" /><div className="callout mb-5 flex gap-3"><Brain className="mt-0.5 shrink-0" size={18} />系统不会用老师口吻自动回复。相似问题可参照同一草稿处理，公开时不展示学生身份。</div><section className="panel"><div className="panel-header"><h2>待教师处理</h2><Badge tone={pending.length ? "amber" : "green"}>{pending.length} 条</Badge></div>{pending.length ? pending.map((q) => <article className="question-card" key={q.id}><div className="question-head"><div className="flex flex-wrap gap-2"><Badge tone="blue">{q.subject}</Badge><Badge tone="zinc">{q.category}</Badge><Badge tone={q.urgency === "attention" ? "red" : "amber"}>{q.urgency === "attention" ? "需要关注" : "普通"}</Badge></div><span className="row-meta">{q.studentName} · {formatChineseDate(q.createdAt, true)}</span></div><p className="question-text">{q.content}</p><div className="question-ai"><strong>AI 分类：</strong>{q.knowledgePoint}<br /><strong>给学生的分步提示：</strong>{q.hint}</div><TeacherQuestionReply id={q.id} draft={q.draft} /></article>) : <div className="empty-state"><span className="empty-state-icon"><CircleHelp /></span><h3>暂时没有待处理问题</h3><p>新问题会先经过 AI 整理，再出现在这里。</p></div>}</section><section className="panel mt-5"><div className="panel-header"><h2>已处理</h2><span className="text-xs text-zinc-500">点击展开即可修改答案</span></div>{handled.map((q) => <details className="handled-question" key={q.id}><summary><span className="row-main"><span className="flex gap-2"><Badge tone="green">已回复</Badge>{q.isPublic && <Badge tone="blue">已公开</Badge>}<Badge>{q.subject}</Badge></span><span className="row-title mt-2 block">{q.content}</span><span className="row-meta">{q.knowledgePoint}</span></span><span className="record-open-label">修改解答</span></summary><div className="px-4 pb-4"><TeacherQuestionReply id={q.id} draft={q.answer?.content ?? q.draft} defaultPublic={q.isPublic} editing /></div></details>)}</section></main>; }
