import { ArrowLeft, CheckCircle2, Download, FileText, UserRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { getAssignmentForTeacher } from "@/lib/data";
import { requireSession } from "@/lib/dal";
import { formatChineseDate } from "@/lib/utils";

function readableAnswers(value: string) { try { return Object.values(JSON.parse(value) as Record<string,string>).filter(Boolean); } catch { return []; } }
export default async function TeacherAssignmentDetail({ params }: { params: Promise<{ id: string }> }) { const session = await requireSession("teacher"); const { id } = await params; const data = await getAssignmentForTeacher(id, session.user.id); if (!data) notFound(); return <main className="page-wrap"><PageHeader title={data.assignment.title} description={`${data.assignment.subject} · 截止 ${formatChineseDate(data.assignment.dueAt, true)}`} actions={<Link className="side-link border border-zinc-200 bg-white" href="/teacher/assignments"><ArrowLeft size={17} />返回作业</Link>} /><div className="content-grid two"><section className="panel"><div className="panel-header"><h2>作业内容</h2><Badge tone="green">已发布</Badge></div><div className="panel-body"><p className="text-sm leading-7 text-zinc-700">{data.assignment.description}</p>{data.assignment.fileId && <a className="attachment-link" href={`/api/files/${data.assignment.fileId}`}><FileText size={18} /><span><strong>作业附件</strong><small>点击查看或下载原文件</small></span><Download size={17} /></a>}<div className="mt-5 grid gap-3">{data.items.length ? data.items.map((item, index) => <div className="rounded-md border border-zinc-200 p-4" key={item.id}><strong className="text-sm">{index + 1}. {item.prompt}</strong><p className="mt-2 text-xs text-zinc-500">{item.type === "single" ? "单选题" : "简答题"} · {item.points} 分 · 参考答案：{item.answer}</p></div>) : <div className="empty-state min-h-36"><p>该作业以文件或任务说明为主，没有在线题目。</p></div>}</div></div></section><aside className="panel"><div className="panel-header"><h2>完成情况</h2><span className="text-xs text-zinc-500">{data.submissions.length} 人提交</span></div>{data.submissions.length ? data.submissions.map((submission) => <details className="submission-row" key={submission.id}><summary><span className="row-icon"><UserRound size={18} /></span><span className="row-main"><span className="row-title">{submission.studentName}</span><span className="row-meta">{submission.submittedAt ? formatChineseDate(submission.submittedAt, true) : "尚未提交"}</span></span><Badge tone="green"><CheckCircle2 size={13} className="mr-1" />{submission.score ?? "待批改"} 分</Badge></summary><div className="submission-detail"><strong>学生答案</strong>{readableAnswers(submission.answersJson).map((answer, index) => <p key={index}>{answer}</p>)}{!readableAnswers(submission.answersJson).length && <p>没有文字答案</p>}<strong>批改反馈</strong><p>{submission.feedback || "尚未填写反馈"}</p></div></details>) : <div className="empty-state min-h-52"><UserRound size={30} className="text-zinc-400" /><h3>暂时没有学生提交</h3><p>学生提交后，会在这里显示答案、分数和批改状态。</p></div>}</aside></div></main>; }
