import { BookOpenCheck, CircleHelp, ClipboardCheck, MessageSquare, TrendingDown, Video } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { StatBlock } from "@/components/stat-block";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { getTeacherData } from "@/lib/data";
import { requireSession } from "@/lib/dal";
import { formatChineseDate } from "@/lib/utils";

export default async function TeacherDashboard() {
  const session = await requireSession("teacher"); const data = await getTeacherData(session.user.id); if (!data) return null;
  const pending = data.questions.filter((q) => q.status === "pending"); const rates = data.assignments.map((a) => Math.round(a.submitted / a.total * 100)); const rate = rates.length ? Math.round(rates.reduce((a,b) => a+b, 0) / rates.length) : 0;
  return <main className="page-wrap"><PageHeader title={`早上好，${session.user.name?.slice(0,1)}老师`} description={`${data.classroom.name} · 今天先处理最需要回应的事情`} /><section className="stats-grid"><StatBlock href="/teacher/questions" label="待处理问题" value={pending.length} note={pending.some((q) => q.urgency === "attention") ? "含需要关注的求助" : "AI 已完成分类"} icon={CircleHelp} tone="amber" /><StatBlock href="/teacher/assignments" label="平均提交率" value={`${rate}%`} note="本班已发布作业" icon={ClipboardCheck} /><StatBlock href="/teacher/students" label="薄弱知识点" value="2" note="分数意义、阅读表达" icon={TrendingDown} tone="coral" /><StatBlock href="/teacher/messages" label="未读提醒" value={data.notifications.filter((n) => !n.readAt).length} note="问题、提交与留言" icon={MessageSquare} tone="blue" /></section><div className="content-grid two"><section className="panel"><div className="panel-header"><h2>优先待办</h2><Link href="/teacher/questions" className="text-xs font-bold text-emerald-700">全部问题</Link></div>{pending.length ? pending.slice(0,3).map((q) => <Link className="list-row" href="/teacher/questions" key={q.id}><span className="row-icon"><CircleHelp size={18} /></span><span className="row-main"><span className="flex flex-wrap gap-2"><Badge tone={q.urgency === "attention" ? "red" : "amber"}>{q.urgency === "attention" ? "需关注" : "待回复"}</Badge><Badge tone="blue">{q.subject}</Badge></span><span className="row-title mt-2 block">{q.content}</span><span className="row-meta">{q.studentName} · {q.knowledgePoint} · {formatChineseDate(q.createdAt, true)}</span></span></Link>) : <div className="empty-state"><BookOpenCheck size={34} className="text-emerald-700" /><p>问题已全部处理</p></div>}</section><aside className="grid content-start gap-4"><section className="panel"><div className="panel-header"><h2>作业进度</h2><Link href="/teacher/assignments" className="text-xs font-bold text-emerald-700">管理</Link></div><div className="panel-body grid gap-4">{data.assignments.slice(0,3).map((item) => <div key={item.id}><div className="mb-2 flex justify-between gap-3 text-sm"><strong>{item.title}</strong><span>{item.submitted}/{item.total}</span></div><Progress value={item.submitted / item.total * 100} /></div>)}</div></section><section className="panel"><div className="panel-header"><h2>快捷入口</h2></div><div className="grid grid-cols-2 gap-2 p-3"><Link className="side-link border border-zinc-200" href="/teacher/materials"><BookOpenCheck size={18} />AI 备课</Link><Link className="side-link border border-zinc-200" href="/teacher/videos"><Video size={18} />发布微课</Link></div></section></aside></div></main>;
}
