"use client";

import { Plus, Send, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { FormStatus } from "@/components/form-status";
import { queuedJsonRequest } from "@/lib/offline-queue";

type Item = { prompt: string; type: "single" | "short"; options: string; answer: string; points: number };
export function AssignmentCreateForm() {
  const router = useRouter(); const [items, setItems] = useState<Item[]>([{ prompt: "", type: "single", options: "A. 选项一\nB. 选项二", answer: "A", points: 100 }]);
  const [state, setState] = useState<{ type: "idle" | "loading" | "success" | "error"; text?: string }>({ type: "idle" });
  function update(index: number, patch: Partial<Item>) { setItems((old) => old.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setState({ type: "loading", text: "正在发布..." }); const source = new FormData(form); const due = new Date(String(source.get("dueAt"))).toISOString(); const payload = { title: source.get("title"), subject: source.get("subject"), description: source.get("description"), dueAt: due, items: items.map((item) => ({ ...item, options: item.type === "single" ? item.options.split("\n").map((v) => v.trim()).filter(Boolean) : [] })) }; const body = new FormData(); body.set("payload", JSON.stringify(payload)); const file = source.get("file") as File; if (file?.size) body.set("file", file); const response = await fetch("/api/assignments", { method: "POST", body }); const result = await response.json(); if (!response.ok) return setState({ type: "error", text: result.error }); setState({ type: "success", text: "作业已发布并通知学生。" }); form.reset(); router.refresh(); }
  return <form className="form-grid" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-3"><div className="field sm:col-span-2"><label>作业名称</label><input className="input" name="title" required /></div><div className="field"><label>学科</label><select className="select" name="subject"><option>数学</option><option>语文</option><option>科学</option><option>英语</option></select></div></div><div className="field"><label>任务说明</label><textarea className="textarea" name="description" required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="field"><label>截止时间</label><input className="input" name="dueAt" type="datetime-local" required /></div><div className="field"><label>作业照片或文件（可选）</label><input className="input h-auto py-2" name="file" type="file" accept="image/*,.pdf,.docx,.pptx,.txt" /><span className="helper">支持图片、PDF、Word、PPT 和 TXT，最大 20MB</span></div></div><div className="grid gap-3">{items.map((item, index) => <div className="rounded-md border border-zinc-200 bg-zinc-50 p-3" key={index}><div className="mb-3 flex items-center justify-between"><strong className="text-sm">第 {index + 1} 题</strong>{items.length > 1 && <Button type="button" variant="ghost" size="icon" title="删除题目" onClick={() => setItems(items.filter((_, i) => i !== index))}><Trash2 size={16} /></Button>}</div><div className="grid gap-3"><input className="input" placeholder="题目内容" value={item.prompt} onChange={(e) => update(index, { prompt: e.target.value })} required /><div className="grid gap-3 sm:grid-cols-3"><select className="select" value={item.type} onChange={(e) => update(index, { type: e.target.value as Item["type"] })}><option value="single">单选题</option><option value="short">简答题</option></select><input className="input" placeholder="正确答案" value={item.answer} onChange={(e) => update(index, { answer: e.target.value })} required /><input className="input" type="number" min="1" max="100" value={item.points} onChange={(e) => update(index, { points: Number(e.target.value) })} /></div>{item.type === "single" && <textarea className="textarea min-h-20" placeholder="每行一个选项" value={item.options} onChange={(e) => update(index, { options: e.target.value })} />}</div></div>)}</div><div className="flex flex-wrap items-center gap-3"><Button type="button" variant="secondary" onClick={() => setItems([...items, { prompt: "", type: "short", options: "", answer: "", points: 20 }])}><Plus size={17} />添加题目</Button><Button type="submit" disabled={state.type === "loading"}><Send size={17} />发布作业</Button><FormStatus state={state} /></div></form>;
}

export function SubmissionForm({ assignmentId, items, initialAnswers }: { assignmentId: string; items: { id: string; prompt: string; type: string; optionsJson: string; points: number }[]; initialAnswers?: Record<string, string> }) {
  const router = useRouter(); const [answers, setAnswers] = useState<Record<string, string>>(initialAnswers ?? {}); const [state, setState] = useState<{ type: "idle" | "loading" | "success" | "error"; text?: string }>({ type: "idle" });
  async function submit(event: FormEvent) { event.preventDefault(); setState({ type: "loading", text: "正在提交..." }); const { response, queued } = await queuedJsonRequest("/api/submissions", { assignmentId, answers }); if (queued) return setState({ type: "success", text: "已保存到待发送队列，联网后自动提交。" }); const result = await response!.json(); if (!response!.ok) return setState({ type: "error", text: result.error }); setState({ type: "success", text: `提交成功，客观题已自动检查，当前得分 ${result.score} 分。` }); router.refresh(); }
  return <form className="grid gap-5" onSubmit={submit}>{items.map((item, index) => <fieldset className="panel p-4" key={item.id}><legend className="px-1 text-sm font-bold">{index + 1}. {item.prompt}（{item.points} 分）</legend>{item.type === "single" ? <div className="mt-3 grid gap-2">{(JSON.parse(item.optionsJson) as string[]).map((option) => { const labeled = option.match(/^([A-Z])[.、]\s*/); const value = labeled?.[1] ?? option; return <label className="flex cursor-pointer gap-2 rounded-md border border-zinc-200 p-3 text-sm" key={option}><input type="radio" name={item.id} checked={answers[item.id] === value} onChange={() => setAnswers({ ...answers, [item.id]: value })} />{option}</label>; })}</div> : <textarea className="textarea mt-3" value={answers[item.id] ?? ""} onChange={(e) => setAnswers({ ...answers, [item.id]: e.target.value })} placeholder="写下完整思考过程" />}</fieldset>)}<div className="flex flex-wrap items-center gap-3"><Button type="submit"><Send size={17} />提交作业</Button><FormStatus state={state} /></div></form>;
}
