import { BookOpen, CheckCircle2, CircleHelp, ClipboardList, MessageSquareReply, PlayCircle } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { StatBlock } from "@/components/stat-block";
import { Badge } from "@/components/ui/badge";
import { getStudentData } from "@/lib/data";
import { requireSession } from "@/lib/dal";
import { formatChineseDate } from "@/lib/utils";

export default async function StudentDashboard() { const session = await requireSession("student"); const data = await getStudentData(session.user.id); if (!data) return null; const todo = data.assignments.filter((a) => !a.submission); const answered = data.questions.filter((q) => q.answer); return <main className="page-wrap"><PageHeader title={`今天好，${session.user.name}`} description="先完成最紧要的一件事，遇到卡点随时提问" /><section className="stats-grid"><StatBlock href="/student/assignments" label="待完成作业" value={todo.length} note="按截止时间排序" icon={ClipboardList} tone="amber" /><StatBlock href="/student/questions" label="老师新回复" value={answered.length} note="查看分步讲解" icon={MessageSquareReply} tone="blue" /><StatBlock href="/student/growth" label="本周已完成" value={data.assignments.filter((a) => a.submission).length} note="继续保持节奏" icon={CheckCircle2} /><StatBlock href="/student/learn" label="课堂资料" value={data.materials.length + data.videos.length} note="可缓存学习" icon={BookOpen} /></section><div className="content-grid two"><section className="panel"><div className="panel-header"><h2>今天的学习任务</h2><Badge tone={todo.length ? "amber" : "green"}>{todo.length ? "需要完成" : "已完成"}</Badge></div>{todo.map((item) => <Link href={`/student/assignments/${item.id}`} className="list-row" key={item.id}><span className="row-icon"><ClipboardList size={18} /></span><span className="row-main"><span className="flex gap-2"><Badge tone="blue">{item.subject}</Badge></span><span className="row-title mt-2 block">{item.title}</span><span className="row-meta">截止 {formatChineseDate(item.dueAt, true)} · {item.description}</span></span></Link>)}{data.videos.slice(0,1).map((video) => <Link href="/student/learn" className="list-row" key={video.id}><span className="row-icon"><PlayCircle size={18} /></span><span className="row-main"><Badge tone="green">老师微课</Badge><span className="row-title mt-2 block">{video.title}</span><span className="row-meta">{video.description}</span></span></Link>)}</section><aside className="grid content-start gap-4"><section className="panel"><div className="panel-header"><h2>老师回复</h2><Link href="/student/questions" className="text-xs font-bold text-emerald-700">查看全部</Link></div>{answered.slice(0,2).map((q) => <div className="list-row" key={q.id}><span className="row-icon"><CircleHelp size={18} /></span><span className="row-main"><span className="row-title">{q.content}</span><span className="row-meta line-clamp-2">{q.answer?.content}</span></span></div>)}</section><Link href="/student/questions" className="panel flex min-h-24 items-center gap-3 p-4 text-emerald-800"><span className="row-icon bg-emerald-50"><CircleHelp /></span><span><strong className="block">有问题？现在问老师</strong><small className="text-zinc-500">可以文字或拍照提交</small></span></Link></aside></div></main>; }
